export PATH="$HOME/.rbenv/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
eval "$(rbenv init -)"
alias gco="git checkout"
alias ga="git add"
alias gc="git commit"
alias rs="rails server"
alias dc="docker-compose"
alias app="cd ~/Projects/line5"
alias forms="cd ~/Projects/line5_forms"
alias ks="lsof -wni tcp:3000"
alias spc="screen -d -m emacs"
alias vin="echo 1N4AL3APXEC320737 | pbcopy"
alias rpp="DISABLE_SPRING=true rake parallel:prepare"
alias weather="curl wttr.in"
source ~/.profile
