export PATH="$HOME/.rbenv/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
eval "$(rbenv init -)"
alias gp="git pull"
alias gpo="git pull origin"
alias gco="git checkout"
alias ga="git add"
alias gc="git commit"
alias rs="rails server thin"
alias dc="docker-compose"
alias gcm="git checkout master"
alias gs="git stash"
alias gsl="git stash list"
alias gsp="git stash pop"
alias td="vim ~/.todo.md"
alias home="cd ~/"
alias app="cd ~/Projects/line5"
alias forms="cd ~/Projects/line5_forms"
alias ks="lsof -wni tcp:3000"
source ~/.profile
