export PATH="$HOME/.rbenv/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
eval "$(rbenv init -)"
alias gpu="git push -u origin"
alias gco="git checkout"
alias ga="git add"
alias gc="git commit"
alias rs="rails server"
alias dc="docker-compose"
alias gs="git stash"
alias gsl="git stash list"
alias gsp="git stash pop"
alias home="cd ~/"
alias app="cd ~/Projects/line5"
alias forms="cd ~/Projects/line5_forms"
alias ks="lsof -wni tcp:3000"
alias fix_test_db="bin/rails db:environment:set RAILS_ENV=test && rake db:drop RAILS_ENV=test && rake db:create RAILS_ENV=test && rake db:migrate RAILS_ENV=test"
alias clean_schema="git checkout db/"
alias spc="screen -d -m emacs"
alias vin="echo 1N4AL3APXEC320737 | pbcopy"
source ~/.profile
